ProfessionalLinuxUsersGroup/psc

README.md, src/contributing.md
Should be in a final initial state now (probably not).
=> fix: replace all lac repo mentions

.github/workflows/mdbook.yml
Same change made to the `lac` repository. Utilizes caching to minimize build time.
=> feat: Optimize github action to utilize caching

src/u1ws.md
Style fixes to match style guide. Closes #11
=> style: Update u1ws to match style guide

src/u1lab.md
=> style: Format unit 1 lab

src/u1lab.md, src/u1ws.md
Adds pictures to lab, fixes broken link in worksheet
=> fix: Unit 1 worksheet and lab patch

README.md, src/intro.md, src/u1ws.md
Should close #17 and close #18
=> fix: refactoring for security, fixing links, adding unit 1 embed

src/SUMMARY.md, src/project.md
Converted final project outline to markdown and added before the Unit 1 section. Closes #27
=> Add final project outline

book.toml, src/u1intro.md, src/u1ws.md, theme/css/variables.css
This commit also adds the unit 1 intro and fixes up the unit 1 worksheet
Closes #8
=> feat: port over lac changes

src/u1ws.md, src/u2intro.md, src/u2lab.md
Thank you Mr. Enzo, congrats again on your job sir!
=> fix: some spelling, spacing, style guide stuff

src/u2ws.md
Added the unit 2 recording embed to `u2ws.md`.
=> feat: Add unit 2 recording

src/assets/downloads/u2/u2_lab.txt
add: download section with .txt's and .doc's
fix: code blocks malformed from copy paste
fix: malformed command
fix: add .txt for u2_lab
fixed: malformed .txt output
=> fixed/add: added .txt for u2_lab,  fixed malformed .txt output

README.md, src/u1lab.md
Changed to MD links, added link to current deployment in README
=> fix: Fix unit 1 lab images

src/SUMMARY.md, src/development.md, src/syllabus.md, src/unitindex.md
Adds course syllabus, schedule, and table of contents to the book
=> chore: port over lac changes

src/syllabus.md, src/u2lab.md
Text inside the warning div was not supporting markdown. Changed to HTML.
=> fix: Code text in warning div not rendering with markdown

src/u4ws.md
=> feat: Add unit 4 worksheet

src/u3lab.md
Prettier also coming in hot... it's so opinionated...
=> fix: incorrect image for checklist import

src/SUMMARY.md, src/certify.md
Added a page outlining the requirements for earning the certification.
Closes #68
=> feat: Add certification info

src/u5ws.md
=> u5ws first pass, needs embedded video recording in near future

scripts/generate_resources.sh
Just reflects the changes made to the resource gen script in the lac repo.
=> chore: Update resource gen script to reflect changes in lac

src/u6intro.md
=> feat: Add unit 6 intro

src/u8lab.md
fix(u8lab): list spacing fixes
=> fix(u8lab): add page title

src/u8lab.md
Fixed indentation, removed the `a.`, `i.`, etc (taken care of with markdown list items)
=> fix: Add header title, syntax and indentaion fixes

src/u8lab.md
Misc fixes, also switched over to fenced code blocks instead of single backtick code snippets.
=> fix: Misc fixes of things encountered during lecture

src/u8ws.md
=> Fixed stupid html quoting

src/u8intro.md
=> feat: First pass on unit 8 intro

src/u9lab.md, src/u9ws.md
First pass of U9 Worksheet and Lab. Worksheet will need the embedded YT recording when it becomes available.
=> First Pass

book.toml
Reflects change made in lac. Points to new issue page instead of all issues.
=> refactor: Point 'suggest an edit' button to new issue page

src/certify.md
Matches PR made to the lac repo (https://github.com/ProfessionalLinuxUsersGroup/lac/pull/284)
Updated discussion post location to the forums, clarified some wording.
=> chore(docs): Update cert info to match lac repo

src/contributors.md
Add your contact details as you see fit.
=> Add contributor page content
